### ISSUE TITLE
[ESP32-S3][v3.2.0] Fatal Error: mbedtls/net.h Missing – Works on v1.0.6[ESP32] but Fails on v3.2.0

### ISSUE THREAD

**Issue by Gopijackson** [aws-samples/arduino-aws-greengrass-iot#16]
I'm trying to compile a project using the ESP32-S3 with the ESP32 board package version 3.2.0, but I'm getting the following error:
```
In file included from c:\Users\gopia\OneDrive\Documents\Arduino\ESP32\greengrass\libraries\AwsGreenGrassIoT\src/network_interface.h:35,
                 from c:\Users\gopia\OneDrive\Documents\Arduino\ESP32\greengrass\libraries\AwsGreenGrassIoT\src/aws_iot_mqtt_client.h:57,
                 from c:\Users\gopia\OneDrive\Documents\Arduino\ESP32\greengrass\libraries\AwsGreenGrassIoT\src/AWSGreenGrassIoT.h:20,
                 from C:\Users\gopia\OneDrive\Documents\Arduino\ESP32\greengrass\gg_temp_humid_pub_sub\gg_temp_humid_pub_sub.ino:22:
c:\Users\gopia\OneDrive\Documents\Arduino\ESP32\greengrass\libraries\AwsGreenGrassIoT\src/network_platform.h:26:10: fatal error: mbedtls/net.h: No such file or directory
   26 | #include "mbedtls/net.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: exit status 1
```

This code compiles and runs fine with version 1.0.6 on the regular ESP32.

Could you please help me understand what has changed in the newer versions, and what I should modify or configure to make this work with the ESP32-S3 and board package v3.2.0?
Is there a recommended way to include or replace mbedtls/net.h for compatibility with newer ESP32 cores?

Thank you!
